### ISSUE TITLE
Consider adding a mention that this project is a fork of python-decouple

### ISSUE THREAD

**Issue by fgmacedo** [osantana/prettyconf#13]
As the [original commit](https://github.com/osantana/prettyconf/commit/3c2a6cbdbfa524f6f7bb2f9d7bef71013c9d7049) is equal to [python-decouple](https://github.com/henriquebastos/python-decouple).

Best regards!

**Comment by osantana** [comment]
Hi @fgmacedo,
1. It's not a fork and the commit are completely different. I started the project from scratch and keep only the same API of python-decouple.
2. The API is the same but the implementation is almost completely different.
3. The code that are similar or equal are contributions that I made to decouple (except the `._caller_path()` method).
4. There are references to python-decouple here: http://prettyconf.readthedocs.org/en/latest/faq.html#why-use-prettyconf-instead-of-python-decouple
