### ISSUE TITLE
The FAQ answer is not correct anymore

### ISSUE THREAD

**Issue by techtonik** [osantana/prettyconf#16]
[FAQ](https://github.com/osantana/prettyconf/blob/master/docs/source/faq.rst#what-is-the-difference-between-prettyconf-and-python-decouple) says:
```
+---------------+-----------------+---------------------+
| Lookup Order  | prettyconf      | python-decouple     |
+---------------+-----------------+---------------------+
| 1             | ENVVAR          | .env                |
| 2             | .env            | settings.ini        |
| 3             | *.cfg or *.ini  | ENVVAR              |
+---------------+-----------------+---------------------+
```

But this is not true anymore:

https://github.com/henriquebastos/python-decouple#overriding-config-files-with-environment-variables

**Comment by osantana** [comment]
Just for confirmation: You say the python-decouple column is incorrect, right?

**Comment by techtonik** [comment]
It depends on `Lookup Order` column meaning. `python-decouple` link says "environment variables have precedence over config files", so I assume that ENVVAR should be first in the lookup order.

**Comment by osantana** [comment]
> It depends on Lookup Order column meaning. python-decouple link says "environment variables have precedence over config files", so I assume that ENVVAR should be first in the lookup order.

Yes. You are correct. This is the new behaviour of python-decouple and I did not updated the FAQ accordingly.

The old python-decouple's behaviour was the main reason why I created prettyconf. I reported this issue in https://github.com/henriquebastos/python-decouple/issues/9 and even tried to "fix" python-decouple but this change could break projects that uses python-decouple.

**Comment by techtonik** [comment]
The lookup table is a very good invention - it is much easier to read than plain English text. I don't think you should just kill tables - try to contribute them stuff to `python-decouple` - as pre-2.9 and 3.0 comparison or just two columns description.

With tables you can even showcase the advantages of extensibility of your project - by pasting actual code snippets side by side.

**Comment by techtonik** [comment]
And you can also place this table into project HISTORY, which will answer the question why this library was written in the first place.

**Comment by osantana** [comment]
Ok. I'll try to make this ASAP.

**Comment by techtonik** [comment]
It is better to state exact version - instead of now say something line 1.0+
