### ISSUE TITLE
A new configuration discovery strategy.

### ISSUE THREAD

**Issue by hernantz** [osantana/prettyconf#18]
If I write an app which has code in `/opt/app` and I would like users to optionally put a `config.ini` in `/etc/app/`, there is no way to do it through prettyconf's current discovery strategy.
It would be nice to be able to configure this behavior.
I imagine something like:
```python
from prettyconf.configuration import env_vars, dirs, recursive

config.strategies = [
     env_vars, 
     dirs('/etc/app', '~/.configs/app'], 
     recursive(root_dir='/', starting_path='./')
]
```
The above snippet means that a config variable would be first checked within the environment variables,
if it is not found there, it would look at `/etc/app`, etc.

What do you think? I'm currently facing this issue and I'm willing to work on this.

**Comment by osantana** [comment]
I like this approach. But I'd use classes to implement strategies just to keep uniformity on API:

```python
from prettyconf.discovery import Environment, Directory, Search, CommandLine

config.strategies = [
    CommandLine(...),  # nice-to-have: enable configuration using command-line/argparse
    Environment(),
    Directory('~/.config/app', '/etc/app'),
    Search(root_dir='/', starting_path=os.path.dirname(__file__)),
]
```

**Comment by hernantz** [comment]
Sounds good to me. 
What are your thoughts on having something similar to `Directory()` called `Files()` that would look for configuration files with specific names:
```python
Files('~/.config/app/app.cfg', '/etc/app/app.cfg')
```

`CommandLine(...)` strategy is very interesting too, maybe it can receive `sys.argv` or maybe something else after the args parsing has been handled by another library?
