### ISSUE TITLE
Propagates root_path configuration (Configuration)

### ISSUE THREAD

**Issue by georgeyk** [osantana/prettyconf#8]
Use case: using prettyconf in docker (or when a project is deployed to a different location not under home directory)

**Comment by osantana** [comment]
I did not understand the use case. Can you elaborate more (with some example)?

**Comment by Fedalto** [comment]
`ConfigurationDiscovery()` raises `InvalidPath('Invalid root path given')` because `self.starting_path` is outside the home directory (`self.root_path`).

**Comment by osantana** [comment]
Understood... @erickwilder I think we need to talk about this issue before fix it...

**Comment by erickwilder** [comment]
@georgeyk, @osantana 
Are we going to change/refactor the actual implementation or just make a quick fix and use `/` as the default `root_path` instead of the home directory?
